# Generated by Django 6.1.1 on 2026-09-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('service', 'Service'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('inspection', 'Inspection'), ('replacement', 'Replacement'), ('other', 'Other')], default='service', max_length=30)),
                ('service_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.asset')),
            ],
        ),
    ]
