# Generated by Django 6.1.1 on 2026-09-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('warranty', 'Warranty Card'), ('receipt', 'Service Receipt'), ('manual', 'User Manual'), ('insurance', 'Insurance'), ('property', 'Property Document'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.asset')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.home')),
            ],
        ),
    ]
