# Generated by Django 6.1.1 on 2026-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_reference_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='maintenance_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='home',
            name='warranty_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
